name: check and build
on: [push]
jobs:
  build_publish_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build docker image
        uses: actions/docker/cli@master
        with:
          args: build -t tartiflette_plugin_scalar .
      - name: style
        uses: actions/docker/cli@master
        with:
          args: run -i tartiflette_plugin_scalar make style
      - name: functional test
        uses: actions/docker/cli@master
        with:
          args: run -i tartiflette_plugin_scalar make test-functional
      - name: unit test
        uses: actions/docker/cli@master
        with:
          args: run -i tartiflette_plugin_scalar make test-unit
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: build and publish to pypi
        uses: ./.github/actions/pypi/
        if: github.ref != 'refs/heads/master'
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
